export { MonacoInput as MonacoEditor } from './MonacoInput';

export * from './BgImg';
export * from './ColorPicker';
export * from './Divider';
export * from './Empty';
export * from './FormTitle';
export * from './WidgetInfo';
export * from './ZoomMode';
export * from './CutCover';
// export * from './MonacoEditor';
export * from './NumberPicker';
export * from './ArrayTabs';
export * from './MyFormCollapse';
export * from './Select';
export * from './BlurInput';
export * from './DecorateSelect';
export * from './NumberPickerUnit';
export * from './MonacoInput';
export * from './CompLayout';
export * from './ImageSelect';
export * from './Slider';
export * from './Palette';
