import { createSchemaField } from '@formily/react';
import { FormItem, FormTab, FormGrid, Input, Switch, Radio, ArrayItems, Space, FormCollapse } from '@formily/antd';
import {
  Select,
  NumberPicker,
  BgImg,
  ColorPicker,
  Divider,
  SettingsEmpty as Empty,
  FormTitle,
  WidgetInfo,
  ZoomModeRadio,
  CutCover,
  MonacoEditor,
  ArrayTabs,
  MyFormCollapse,
  DecorateSelect,
  NumberPickerUnit,
  CompLayout,
  ImageSelect,
  Slider,
  Palette,
} from './components';

export const SchemaField = createSchemaField({
  components: {
    FormItem,
    FormTab,
    FormGrid,
    Select,
    Input,
    NumberPicker,
    BgImg,
    ColorPicker,
    Divider,
    Empty,
    FormTitle,
    WidgetInfo,
    ZoomMode: ZoomModeRadio,
    CutCover,
    MonacoEditor,
    Switch,
    ArrayTabs,
    FormCollapse,
    MyFormCollapse,
    Radio,
    ArrayItems,
    Space,
    DecorateSelect,
    NumberPickerUnit,
    CompLayout,
    ImageSelect,
    Slider,
    Palette,
  },
});
